//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phipgn_csharp_selenium_demo.HybridDriven {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Locators : global::System.Configuration.ApplicationSettingsBase {
        
        private static Locators defaultInstance = ((Locators)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Locators())));
        
        public static Locators Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@id=\'twotabsearchtextbox\']")]
        public string SearchBox {
            get {
                return ((string)(this["SearchBox"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\'searchDropdownBox\']")]
        public string SearchDropdownBox {
            get {
                return ((string)(this["SearchDropdownBox"]));
            }
            set {
                this["SearchDropdownBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Go\']")]
        public string BtnSearch {
            get {
                return ((string)(this["BtnSearch"]));
            }
            set {
                this["BtnSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//span[contains(@cel_widget_id, \'MAIN-SEARCH_RESULTS\')])[1]//h2/a")]
        public string FirstResult {
            get {
                return ((string)(this["FirstResult"]));
            }
            set {
                this["FirstResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\'productTitle\']")]
        public string ProductTitle {
            get {
                return ((string)(this["ProductTitle"]));
            }
            set {
                this["ProductTitle"] = value;
            }
        }
    }
}
